(function(){
google.isOpera=false;google.isIE=false;google.isSafari=true;google.isSafari=false;
google.time=function(){return(new Date).getTime()};google.log=function(a,c){(new Image).src="/gen_204?atyp=i&ct="+a+"&cad="+c+"&zx="+google.time()};google.xhr=function(){var a=null;try{a=new XMLHttpRequest}catch(c){}return a};
google.getComputedStyle=function(a,c,d){var b=d?"":0;var e=document.defaultView&&document.defaultView.getComputedStyle(a,"");b=e.getPropertyValue(c);b=d?b:parseInt(b,10);return b};google.getHeight=function(a){return google.getComputedStyle(a,"height")};google.getWidth=function(a){return google.getComputedStyle(a,"width")};google.getPageOffsetTop=function(a){return a.offsetTop+(a.offsetParent?google.getPageOffsetTop(a.offsetParent):0)};google.getPageOffsetLeft=function(a){return a.offsetLeft+(a.offsetParent?
google.getPageOffsetLeft(a.offsetParent):0)};google.getPageOffsetStart=function(a){return google.getPageOffsetLeft(a)};google.getColor=function(a){return google.getComputedStyle(a,"color",true)};google.rhs=function(){};google.bind=function(a,c,d){a.addEventListener(c,d,false);};
})();
(function(){
window.google.stringify=function(a){var c,d,j,b="",f;switch(typeof a){case "object":if(a)if(a instanceof Array||typeof a.join=="function"&&typeof a.reverse=="function"){for(d=0;d<a.length;++d){f=window.google.stringify(a[d]);if(b)b+=",";b+=f}return"["+b+"]"}else if(typeof a.toString!="undefined"){for(d in a){f=a[d];if(typeof f!="undefined"&&typeof f!="function"){f=window.google.stringify(f);if(b)b+=",";b+=window.google.stringify(d)+":"+f}}return"{"+b+"}"}return"null";case "number":return isFinite(a)?
String(a):"null";case "string":j=a.length;b='"';for(d=0;d<j;d+=1){c=a.charAt(d);if(c>=" "){if(c=="\\"||c=='"')b+="\\";b+=c}else switch(c){case "\n":b+="\\n";break;case "\r":b+="\\r";break;case "\t":b+="\\t";break;default:c=c.charCodeAt();b+="\\u00"+Math.floor(c/16).toString(16)+(c%16).toString(16);break}}return b+'"';case "boolean":return String(a);default:return"null"}};google.History={};var e=[],g="#";google.History.client=function(a){e.push(a);return e.length-1};var h,i;function k(){var a=h.value;i=!(!a)?eval("("+a+")"):{}}google.History.save=function(a,c){if(h){k();if(!i[g])i[g]={};i[g][a]=c;h.value=google.stringify(i)}};function l(){i=null;h=document.getElementById("hcache");h&&window.setTimeout(function(){k();for(var a=0;a<e.length;++a)if(i&&i[g]&&i[g][a])e[a].call(null,i[g][a])},0)}l();google.rein.push(function(){g=google.pageState;l()});
})();
(function(){
var a,b;google.rhs=function(){if(!google.drhs)if(document.getElementById("mbEnd")&&(a||b)){var d=google.getHeight(document.getElementById("rhsline")),c=a?google.getHeight(a):0;if(b)c+=google.getHeight(b)+18;document.getElementById("rhspad").style.height=c>d?Math.min(9999,c-d)+"px":(google.isIE?"":0)}};function e(){a=document.getElementById("tads");b=document.getElementById("3po");google.rhs()}e();google.bind(window,"resize",google.rhs);google.rein.push(e);
})();
(function(){
var f=0,g=[];google.fx={};google.fx.linear=function(a){return a};google.fx.easeOut=function(a){return 1-Math.pow(1-a,3)};google.fx.easeInAndOut=function easeInAndOut(a){return(3-2*a)*a*a};google.fx.animate=function(a,d,e){for(var c=0,b;b=d[c++];){b[5]=b[5]==null?"px":b[5];b[4]=b[4]||google.fx.linear;h(b[0],b[1],b[2]+b[5])}g.push({b:a,a:e,d:google.time(),c:d});f=f||window.setInterval(i,15)};function i(){for(var a=0,d;d=g[a++];)j(d)||g.splice(--a,1);if(!g.length){window.clearInterval(f);f=0}}function j(a){var d=
google.time()-a.d;if(d>=a.b){for(var e=0,c;c=a.c[e++];)h(c[0],c[1],c[3]+c[5]);a.a&&a.a();return 0}else{for(var e=0,c;c=a.c[e++];){var b=c[2]+(c[3]-c[2])*c[4](d/a.b);if(c[5]=="px")b=Math.round(b);h(c[0],c[1],b+c[5])}return 1}}function h(a){for(var d=1;d<arguments.length;d+=2){var e=arguments[d],c=arguments[d+1],b=a.style;if(b&&e in b)b[e]=c;else if(e in a)a[e]=c;}return a}google.fx.wrap=function(a){var d=document.createElement("div");a.parentNode.replaceChild(d,a);d.appendChild(a);return d};google.fx.unwrap=function(a){a.parentNode.parentNode.replaceChild(a,a.parentNode)};
})();
(function(){
var e=true,g=null,h=false,aa=h,k,l,m,n,o="",q=g,r=g,s=g,t=-1,u,v,x,y,z,A,B,C,ba,D=0,E=0,ca=h,G=g,H=0,I;var da;var K;var P;var Q,S,ea,fa,ha,ia,T;
function la(a){var b=a&&a.match(/\D+$/);return b?b[0]:g}var V;
function ma(){if(z){na();W();z.value=A.value=C.value="";window.clearTimeout(q);o=ba="";q=r=s=g;t=-1;V=D=E=H=0;K=0;
da="";}}
function oa(a,b,c,d,j){u=a;v=b;m=n=l=v.value;if(google.ac.m){ia=T=0;Q={};S=Math.random()*100<=google.ac.m}if(!b.init){ha=document.getElementById("csi");google.bind(v,"paste",pa);I=document.getElementsByTagName("head")[0];google.bind(u,"submit",qa);v.setAttribute("autocomplete","off");google.bind(v,"blur",W);v.onkeypress=X;google.bind(v,"keyup",ra);z=ta("aq","f");A=ta("oq",m);C=ta("aqi","");x=document.createElement("table");x.cellSpacing=x.cellPadding="0";y=x.style;x.className="gac_m";u.appendChild(x);b.init=e}W();ua();if(!aa){va();aa=e}V=0;var f="&client=hp";if(c=="i"){V=2;f="&client=img"}else if(d&&d!=""){V=1;f="&client=serp"}var p=["?hl=",google.kHL,f,(c?"&ds="+c:""),(d?"&pq="+encodeURIComponent(d):""),(j?"&tok="+encodeURIComponent(j):"")].join("");ba="/complete/search"+p;da="/complete/deleteitems"+p;K=wa(v);
google.bind(window,"pageshow",function(i){if(i.persisted){z.value="f";A.value=v.value}});ya();(new Image).src="http://clients1.google.com/generate_204";}
function va(){var a=document.createElement("style");I.appendChild(a);var b=g;b=a.sheet;var d=function(f,p){var i=
f+" { "+p+" }";b.insertRule(i,b.cssRules.length);};d(".gac_m","cursor:default;line-height:117%;border:1px solid #666;z-index:99;background:white;position:absolute;margin:0;font-size:"+"17px");d(".gac_m td","line-height:22px");d(".gac_n","padding-top:1px;padding-bottom:1px");d(".gac_b td.gac_c","background:#d5e2ff");d(".gac_b","background:#d5e2ff");d(".gac_a td.gac_f","background:#fff8dd");d(".gac_p","padding:1px 4px 2px 3px");d(".gac_u","padding:0 0 1px 0;line-height:117%;text-align:left");
d(".gac_t","width:100%;text-align:left;font-size:"+"17px");d(".gac_bt","width:"+(v.offsetWidth-2)+"px;text-align:center;padding:8px 0 7px");d(".gac_sb","font-size:15px;height:28px;margin:0.2em");d(".gac_s","height:3px;font-size:1px");var j="white-space:nowrap;overflow:hidden;text-align:left;padding-left:3px;padding-right:3px";d(".gac_c",j);d(".gac_d","text-align:right;padding:0 3px;font-size:"+"11px");d(".fl a:link,.fl a:visited","color:#77c");d(".gac_h","color:green");d(".gac_i",
"color:#666");}function ua(){if(x){y.left=za(v,"offsetLeft")+"px";y.top=za(v,"offsetTop")+v.offsetHeight-1+"px";y.width=v.offsetWidth+"px";}}
function ta(a,b){var c=document.createElement("input");c.type="hidden";c.name=a;c.value=b;return u.appendChild(c)}function X(a){var b=a.keyCode;if(b==27&&Aa()){W();Y(m);a.cancelBubble=e;return a.returnValue=h}if(b==13){Ba(h);a.cancelBubble=e;return a.returnValue=h}if(b==38||b==40){E++;E%3==1&&xa(b);return h}}
function Ba(a){if(!a&&B){u.removeChild(B);B=g}if(s&&t!=-1&&ca&&!(a&&s.b))s.onclick(g);else if(v.value=="")W();else{if(a)B=ta("btnI","1");Ca()}}function Ca(){qa();u.onsubmit&&u.onsubmit()==h||u.submit()}function ra(a){var b=a.keyCode;if(!E)xa(b);E=0;}
function pa(){if(S)ea=e}
function xa(a){if(v.value!=l){m=v.value;K=wa(v);A.value=m}if(a==40||a==38){Da(a==40);ca=Aa()}ua();if(o!=m&&!G)G=window.setTimeout(W,500);l=v.value;l==""&&!q&&
ya()}function Ea(){ca=h;if(!H){if(s)s.className="gac_a";s=this;for(var a=0,b;b=Z(a);a++)b==s&&(t=a);s.className="gac_b"}}function Fa(a){return function(){Ga(Ha(a));return h}}
function Ha(a){return[a,"&aq=",s.completeId,"&oq=",A.value,C.value.length>0?"&aqi="+C.value:""].join("")}function Ga(a){var b=window.frames.wgjf;if(b){google.r=1;b.location.replace(a)}else window.location=a}
function Ia(){Y(this.completeString);Ca();}
function Da(a){if(!o&&m){n="";ya()}else if(!(m!=o||!q))if(!(!r||r.length<=0))if(Aa()){if(s)s.className="gac_a";for(var b=r.length,c=(t+1+(a?1:b))%(b+1)-1;c!=-1&&Z(c).a;)c=(c+1+(a?1:b))%(b+1)-1;t=c;if(t==-1)Ja();else{s=Z(c);s.className="gac_b";Y(s.completeString);z.value=s.completeId}}else Na()}function Ja(){v.focus();Y(m);s=g;z.value="f"}
function W(){if(G){window.clearTimeout(G);G=g}y&&(y.visibility="hidden");}function Na(){y&&(y.visibility="visible");ua();H=1}function Aa(){return!!y&&y.visibility=="visible"}
function na(){if(x){x.innerHTML="";}}function Oa(a,b){a.onclick=b?Fa(b):Ia;a.b=!b;a.onmousedown=Pa;a.onmouseover=Ea;a.onmousemove=function(){if(H){H=0;Ea.call(this)}}}
function Qa(a,b){Ra(a);for(var c=0,d;d=Z(c++);)if(d.completeId==b){Sa(da,d.completeString,Ta);break}return h}function Ta(a){for(var b=0,c;c=Z(b++);)if(la(c.completeId)=="p"&&c.completeString==a[0]){c.a=1;c.onclick=c.onmouseover=g;if(c==s){c.className="gac_a";t=-1;Ja()}c.completeCell.className="gac_c gac_i fl";c.completeCell.innerHTML="This search was removed from your \x3ca href\x3d\x22/history\x22\x3eWeb History\x3c/a\x3e"}}
function Ua(a){var b=a[0];var c;if(S&&(c=Q[b]))c.t.rr=google.time();D>0&&D--;if(!x||b!=m){Va(b);}else{function d(Ya,Ka){var La=Ka?la(Ka[2]):g,Ma=Ya+(La?"-"+La:"");if(Ma!=p){if(i)f+=p+i;i=0;p=Ma}i++;j++}if(G){window.clearTimeout(G);G=g}o=a[0];na();
for(var j=0,f="",p,i=0,F=a[1],R=0,w;R<F.length;R++)if(w=F[R])if(w[1]==5){Wa(w,a);d("n",w)}else if(w[1]==8){Xa(w,a,R==0);d("a",w)}else if(w[1]==0){R==0&&$();Za(w);d("g",w)}if(j>0){V==0?ab():$();Na()}else W();
d("");C.value=f;t=-1;r=x.rows;(r&&r.length>0?Na:W)();Va(b,f);}}function Va(a,b){var c;if(S&&(c=Q[a])){if(b!=undefined){c.t.rd=google.time();c.e.aqi=b}var d=google.sn;google.sn="suggest";google.report&&google.report(c,c.e);google.sn=d;delete Q[a]}}
function Z(a){b=r.item(a);return b}
function ab(){var a=x.insertRow(-1);a.a=1;a.onmousedown=Pa;var b=a.insertCell(0);b.innerHTML='<div class=gac_bt><input class=gac_sb type=button value="Google Search" onclick="google.ac.rd(0)"><input class=gac_sb type=button value="I\x26#39;m Feeling Lucky" onclick="google.ac.rd(1)"></div>'}
function Xa(a,b,c){$();var d=a[3],j=d[0].replace(/<\/?[b|em]>/gi,""),f=x.insertRow(-1),p=d[1];Oa(f,p);f.completeId=a[2];f.className="gac_a";f.completeString=b[0];var i=document.createElement("td");i.className="gac_f gac_p";var F=cb("http://"+j,p);i.innerHTML=['<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td><table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td style="line-height:117%"><a class=q ',F,">",d[2],'</a><td class="gac_d gac_i">Sponsored Link</table><tr><td class=gac_u><span class=gac_h',">",d[0],"</span>&nbsp; &nbsp;",d[3],d[4]?" "+d[4]:"","</table>"].join("");f.appendChild(i);c&&$()}
function Wa(a,b){$();var c=x.insertRow(-1),d=a[3],j=d[0];Oa(c,j);c.completeId=a[2];c.className="gac_a";c.completeString=b[0];var f=document.createElement("td");f.className="gac_c gac_n";var p=a[0].replace(/HTTPS?:\/\//gi,""),i=a[0].replace(/<\/?[b|em]>/gi,"");/^HTTPS?:\/\//i.test(i)||(i=(j.indexOf("/url?url=https:")>0?"https":"http")+"://"+i);var F=cb(i,j);f.style.lineHeight="117%";f.innerHTML=["<a ",F,">",d[1],'</a><br><span class="gac_h"',">",p,"</span>"].join("");
c.appendChild(f)}function cb(a,b){return['href="',a,'" onmousedown="google.ac.r(event, this, \'',b,'\')" onclick="return google.ac.c(event)"'].join("")}function eb(a,b,c){k=h;if(a.which)k=a.which==2;else if(a.button)k=a.button==4;b.href=Ha(c)}function fb(a){if(k){Ra(a);return e}return h}
function Ra(a){a.stopPropagation();a.cancelBubble=a.cancel=a.returnValue=e}
function Za(a){var b=x.insertRow(-1);Oa(b);var c=b.completeId=a[2];b.className="gac_a";var d=b.completeCell=document.createElement("td");d.className="gac_c";d.innerHTML=a[0];b.completeString=d.textContent;if(la(a[2])==
"p"){d.className="";d.innerHTML=["<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td class=gac_c>",a[0],'<td class="gac_d fl"><a href=# onclick="return google.ac.dc(event,\'',c,"')\">Remove</a></table>"].join("");}b.appendChild(d)}function $(){var a=x.insertRow(-1);a.a=1;a.onmousedown=Pa;a.insertCell(0).className="gac_s"}
function qa(){W();if(r&&Z(t)&&A.value!=v.value)z.value=Z(t).completeId;else{A.value="";z.value="f";if(D>=10)z.value="o"}}
function ya(){if(m&&n!=m){D++;if(S){ha.value="";var a=m.length-n.length;if(ea){a="p";ea=h}var b=google.time();T||(T=b);Q[m]={t:{start:b},e:{d:a,i:ia++,ts:b-T}};if(fa!=150)Q[m].e.p=fa}Sa(ba,m,Ua);v.focus()}n=m;for(var c=100,d=1;d<=(D-2)/2;d++)c*=2;c+=50;q=window.setTimeout(ya,c);fa=c;}
function Sa(a,b,c){P&&I.removeChild(P);P=document.createElement("script");P.src=["http://clients1.google.com",a,"&q=",encodeURIComponent(b),"&cp="+K].join("");I.appendChild(P);}function Y(a){if(v)v.value=l=a}function za(a,b){for(var c=0;a;){c+=a[b];a=a.offsetParent}return c}
function $a(a,b){a.appendChild(document.createTextNode(b))}function Pa(a){a.stopPropagation();return h}
function wa(a){var b=0,c=0;if(ib(a)){b=a.selectionStart;c=a.selectionEnd}return b&&c&&b==c?b:0}function ib(a){try{return typeof a.selectionStart=="number"}catch(b){return h}}
window.google.ac={i:oa,h:Ua,r:eb,c:fb,rd:Ba,u:Y};window.google.ac.d=Ta;window.google.ac.dc=Qa;google.bind(window,"resize",ua);google.dstr&&google.dstr.push&&google.dstr.push(ma);
})();
(function(){
window.ManyBox={};var e,g,h=1,j=google.History.client(i);function k(a){for(var b in e)if(e[b].c&&a(e[b]))return}function l(a,b,c,d,f){this.c=a;this.i=b;this.B=d;this.o=f;this.q="/mbd?"+(b?"docid="+b:"")+"&resnum="+a.replace(/[^0-9]/,"")+"&mbtype="+d+"&usg="+c+"&hl="+(google.kHL||"");this.e={};this.l="";g[a]={r:0,D:this.e,i:this.i,h:0};this.n=0}l.prototype.append=function(a){this.l+="&"+a.join("&")};function m(a,b){return document.getElementById("mb"+b+a.c)}function n(a,b){a.g.style.paddingTop=b+"px";
a.g.style.display=a.g.innerHTML?"":"none";if(b>a.n)a.n=b}function q(a){if(!a.A){a.A=1;a.d=m(a,"b");a.j=0;a.a=m(a,"l");a.m=a.a.getElementsByTagName("DIV")[0];a.p=a.a.getElementsByTagName("A")[0];a.z=a.p.innerHTML;a.o=a.o||a.z;a.m.title="Click for more information";a.a.F=function(b,c){var d=google.getPageOffsetStart(a.a),f=google.getPageOffsetTop(a.a);return b>d-5&&b<d+google.getWidth(a.a)+5&&c>f-5&&c<f+google.getHeight(a.a)+5};a.g=m(a,"f");n(a,0);a.a.onmousedown=r(a);a.a.onclick=s(a);a.a.go=function(){a.a.onmousedown();
a.a.onclick()}}}function r(a){return function(){if(g[a.c].h){if(a.I++<3)google.log("manybox",[a.j?"close":"open","&id=",a.c,"&docid=",a.i,"&mbtype=",a.B,a.l].join(""))}else{var b=google.xhr();if(b){b.open("GET",a.q+a.l+"&zx="+google.time());a.t=0;b.onreadystatechange=function(){if(b.readyState==4){var c=0;if(b.status==200)try{eval(b.responseText);c=1}catch(d){}if(!c&&!a.C){g[a.c].h=0;a.C=1;a.q+="&cad=retry";a.a.onmousedown()}else{a.u&&w(a);a.t=
0}}};a.t=1;b.send(null)}g[a.c].h=(a.I=1)}}}function s(a){return function(){g[a.c].h||a.a.onmousedown();(a.u=a.t)||w(a)}}function x(a){if(!a.e.k){a.e.k="\x3cfont color\x3dred\x3eError:\x3c/font\x3e The server could not complete your request.  Try again in 30 seconds.";a.G=a.a.onclick;a.a.onclick=function(){h=0;w(a);h=1;a.b.parentNode.removeChild(a.b);g[a.c].h=(a.e.k=(a.v=0));a.a.onclick=a.G}}if(!a.v){a.v=1;var b=document.getElementById("res");a.H=b&&google.getPageOffsetStart(a.d)>google.getPageOffsetStart(b)+google.getWidth(b);a.b=document.createElement("div");n(a,0);a.b.style.position="absolute";
a.b.style.paddingTop=(a.b.style.paddingBottom="6px");a.b.style.display="none";a.b.className="med";var c=document.createElement("div");a.b.appendChild(c);c.className="std";c.innerHTML=a.e.k;a.g.parentNode.insertBefore(a.b,a.g)}}function i(a){h=0;ManyBox.init();k(function(b){if(b.i==a[b.c].i){b.e=a[b.c].D;if(a[b.c].r!=b.j)w(b)}else a[b.c].h=0});g=a;h=1;google.History.save(j,g)}ManyBox.create=function(a,
b,c,d,f){return new l(a,b,c,d,f)};ManyBox.register=function(a,b,c,d,f){return e[a]=ManyBox.create(a,b,c,d,f)};google.bind(document,"click",function(a){a=a||window.event;var b=a.target||a.srcElement;while(b.parentNode){if(b.tagName=="A"||b.onclick)return;b=b.parentNode}k(function(c){if(c.a.F(a.clientX,a.clientY)){c.a.go();return 1}})});function y(){e={};g={};history.navigationMode=history.navigationMode&&"fast"}y();ManyBox.init=function(){k(q)};function z(a,b){a.b.style.clip="rect(0px,"+(a.d.width||
"34em")+","+(b||1)+"px,0px)"}l.prototype.insert=function(a){this.e.k=a;google.History.save(j,g)};function A(a){a.f=m(a,"cb");var b=a.f&&a.f.getAttribute("mbopen");if(b){eval(b);a.onopen(a.f)}}function B(a){a.b.style.display="none";a.m.style.backgroundPosition="-91px -74px";a.p.innerHTML=a.z;a.j=(g[a.c].r=0);google.History.save(j,g)}function C(a,b,c,d,f){var t=c>0?150:75,u=google.time()-f,v=u<t&&h?u/t*c:(d>1?c-10:c),o=Math.max(a.s,b+v),p=o-a.s;z(a,p);a.d.style.height=o<0?0:(p?o+"px":"");n(a,Math.max(0,
p-5));google.rhs();if(Math.abs(v)<Math.abs(c))window.setTimeout(function(){C(a,b,c,d-1,f)},30);else window.setTimeout(function(){c<0?B(a):A(a);if(!google.isIE&&a.H)a.b.style.width="100px";a.b.style.position=(a.d.style.height="");n(a,0);google.rhs();a.d.w=0},0)}function w(a){a.u=0;if(!a.d.w){a.d.w=1;var b;if(!a.j){a.s=google.getHeight(a.d);x(a);n(a,0);a.n=0;k(function(d){d.m.title=""});a.m.style.backgroundPosition="-105px -74px";a.p.innerHTML=a.o;z(a,1);a.b.style.position="absolute";a.b.style.display=
"";a.j=(g[a.c].r=1);google.History.save(j,g);b=a.b.offsetHeight}else{var c=a.f&&a.f.getAttribute("mbclose");if(c){eval(c);a.onclose(a.f)}b=a.s-google.getHeight(a.d);a.g.style.display="none";n(a,a.n);a.b.style.position="absolute"}C(a,google.getHeight(a.d),b,google.isSafari?2:1,google.time())}}google.dstr&&google.dstr.push(y);
})();
(function(){
var h=false,i=true,l,m;
function o(){l=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(l);m=l.sheet;}
google.addCSSRule=function(a,b){l||o();var e=a+"{"+b+"}";m.insertRule(e,m.cssRules.length);};google.acrs=function(a){for(var b=a.split(/{|}/),d=1;d<b.length;d+=2)google.addCSSRule(b[d-1],b[d])};google.Toolbelt={};
var p=null,r=h,s=h,t=document.location.href.match("^.*?://[^/]*")[0],u,v;function x(a,b){v=document.getElementById("tbd");u=v.innerHTML=a;b||google.Toolbelt.toggle(null,null,i);google.j&&google.j.trap&&google.j.trap()}var y=google.History.client(function(a){x(a.content,a.open==google.Toolbelt.isToolbeltOpen())}),z=google.History.client(function(a){google.acrs(a)});google.Toolbelt.ascrs=function(a){google.acrs(a);google.History.save(z,a)};var A=[];google.rein.push(function(){A=[]});
google.Toolbelt.registerToolbeltCallback=function(a){A.push(a)};function B(){for(var a=0,b;b=A[a++];)b()}google.rein.push(function(){A=[]});google.Toolbelt.listeners=function(){return A};
google.Toolbelt.updateTbo=function(a){for(var b=document.getElementsByTagName("A"),d=0,c;c=b[d++];)if(c.href.match("^("+t+")?/(?!url|aclk|[^?]*$)")&&c!=p&&!c.href.match("[?&]tbo=u(&|$)")){c.href=c.href.replace(/([?&])tbo=[^&](&|$)/,"$1")+(a?"&tbo=1":"");}for(var d=0,e;e=document.forms[d++];)if(e.action.match("/search$")){for(var g=0,q=0,j;j=e.elements[q++];)if(j.name==
"tbo"&&!a){j.parentNode.removeChild(j);g=1}if(!g&&a){var k=document.createElement("input");k.type="hidden";k.value="1";k.name="tbo";e.appendChild(k)}}};google.Toolbelt.isToolbeltOpen=function(){return document.body.className.match(/\btbo\b/)!=null};
google.Toolbelt.toggle=function(a,b,d){b=b||window.event;if(a)p=a;b&&b.stopPropagation();v=document.getElementById("tbd");if(!v)return i;u=v.innerHTML;var c=v.getElementsByTagName("DIV").length>0,f=google.Toolbelt.isToolbeltOpen(),e=d||!!document.getElementById("tbt5")||mbtb1.na;if(f&&!s){C(h,e);google.log("toolbelt","0&ei="+google.kEI);r=i}else if(c){C(i,
e);r&&google.log("toolbelt","1&ei="+google.kEI)}else{mbtb1.insert=x;var g=google.xhr();if(g){g.open("GET",[google.pageState?google.pageState.replace("#","/mbd?"):google.base_href.replace(/^\/search\?/,"/mbd?"),"&mbtype=29&resnum=1&tbo=1",mbtb1.tbs?"&tbs="+mbtb1.tbs:"","&docid=",mbtb1.docid,"&usg=",mbtb1.usg,"&zx=",google.time()].join(""));g.onreadystatechange=function(){if(g.readyState==4&&g.status==200)try{eval(g.responseText)}catch(q){window.location.replace(a.href)}};g.send(null);s=i;C(i,e)}return h}google.History.save(y,
{content:u,open:s||!f});return s=h};function E(a){for(;a&&a.className!="tbt";)a=a.parentNode;return a}google.Toolbelt.cdrClk=function(){var a=document.getElementById("cdr_opt");if(a){a.className="tbots";var b=E(a);if(b){for(var d=0,c;c=b.childNodes[d++];)if(c.className=="tbos")c.className="tbotu";var f=document.getElementById("cdr_min");f&&f.focus()}}};function F(a){return a.replace(/_/g,"_1").replace(/,/g,"_2").replace(/:/g,"_3")}
google.Toolbelt.cdrSbt=function(){var a=document.getElementById("cdr_frm");if(a){for(var b,d=0,c;c=a.childNodes[d++];)if(c.nodeType==1&&c.name=="tbs")b=c;var f=F(document.getElementById("cdr_min").value),e=F(document.getElementById("cdr_max").value);b.value=b.value.replace(/(cd_min:)([^,]*)/,"$1"+f).replace(/(cd_max:)([^,]*)/,"$1"+e)}};
google.Toolbelt.tbosClk=function(a){var b=a||window.event,d=b.target||b.srcElement;if(d&&d.className=="tbotu"){d.className="tbos";var c=E(d);if(c)for(var f=0,e;e=c.childNodes[f++];)if(e.className=="tbots")e.className="tbou"}};var G=google.fx.easeOut,H=[["tads","margin-left","marginLeft"],["res","margin-left","marginLeft"],["tbd","margin-left","marginLeft"],["mbEnd","width","width"],["tbt3","left","left"],["tbt8","left","left"],["tbt5","margin-left","marginLeft"]],I=h;
function J(a){for(var b=0,d=0,c;c=H[d++];){var f=document.getElementById(c[0]);f&&a(f,c,b++)}}function K(){var a=[];J(function(b,d){var c=d[1];a.push(c=="width"?b.offsetWidth:google.getComputedStyle(b,c))});return a}
function C(a,b){if(!I){var d=[],c=K(),f=google.getComputedStyle(v,"left",i),e=document.getElementById("cdr_min"),g=document.getElementById("cdr_max");if(e&&g){e.style.width=google.getComputedStyle(e,"width",i);g.style.width=google.getComputedStyle(g,"width",i)}document.body.className=document.body.className.replace(/\btbo\b/,"")+(a?" tbo":"");google.Toolbelt.updateTbo(a);B();if(!b){if(a){f=google.getComputedStyle(v,"left",i);if(e&&g){e.style.width=google.getComputedStyle(e,"width",i);g.style.width=
google.getComputedStyle(g,"width",i)}}var q=K();J(function(k,w,D){d.push([k,w[2],c[D],q[D],G])});var j=google.fx.wrap(v);j.style.position="absolute";j.style.overflow="hidden";j.style.left=f;v.style.display="block";v.style.position="static";I=i;google.fx.animate(a?400:200,d,function(){J(function(k,w){k.style[w[2]]=""});v.style.position="absolute";v.style.display="";google.fx.unwrap(v);if(e&&g){e.style.width="";g.style.width=""}I=h})}}};
})();
(function (){
var aa=false;try{}catch(ca){}var h;if(!window.google.j)window.google.j={};var i=window.google.j,k=window.frames.wgjf,m=location,n;i.ss=1;var o,r="1",da="1",t={c:{1:google.j[1]},s:{}},u,ea,w,x,y,A,B,D=0,E=[],F=[];if(!window.onerror)window.onerror=function(){};function H(b,c,d){c._ls=n;c._fr=!(!k);c._ph=D;if(i.d!=i.ss)c._ss=i.ss+","+i.d;try{c._wlt=typeof m.href;c._flt=typeof k.location.href;c._wl=encodeURIComponent(m.href);c._fl=encodeURIComponent(k.location.href)}catch(e){}var f=[b,d&&d.message||d||
""];for(var g in c)f.push(g+"="+c[g]);window.onerror(f.join(":").substr(0,1900))}function I(b,c,d){try{d?b.replace(c):(b.href=c)}catch(e){H("SL",{v:c,r:d},e)}}var J=false,K=false,L=false,M=false;function fa(b,c,d){if(b[c]){if(!b.__handler){b.__handler=b[c];b[c]=function(e){return this.__handler(e)!=false&&d.call(this,e)}}}else b.__handler=(b[c]=function(e){return d.call(this,e)})}i.trap=function trap(){var b=document.getElementsByTagName("form");for(var c=0,d;d=b[c++];)if(u.test(d.action)&&!/\bnj\b/.test(d.className))fa(d,
"onsubmit",function(e){return ga(this,false,e)})};function N(){return O>i.ss?O:i.ss+1}function P(b){if(!b)return b===0;return b==i.ss&&i.ss>i.d}function ha(b){b.replace(/\x3cscript[\s\S]*?\x3e([\s\S]*?)\x3c\/script/ig,function(c,d){var e=document.createElement("script");e.text=d;document.body.appendChild(e)})}i.bc=function bc(b){try{B=b?b:"";document.body.className=B}catch(c){H("BC",{name:b},c)}};i.p=function p(b,c,d,e){if(Q.ie||P(e)){try{if(c=="sdb"&&J){R(r);window.scroll(0,0);J=false}var f=document.getElementById(c),
g=f.cloneNode(false);g.innerHTML=d;f.parentNode.replaceChild(g,f);if(Q.ie)ha(d);if(c=="main"){var j=S("q")||S("as_q");for(var s=0,z;z=["gs","bgs","f"][s++];)if(document[z])document[z].q.value=j}document.getElementById(c).style.visibility="visible"}catch(v){H("P",{id:c},v)}D=21}};i.ph=function ph(b,c,d){if(Q.ie||P(d)){var e,f;try{E.push(c);for(e in c){f=c[e];document.getElementById(e).href=f}}catch(g){H("PH",{id:e,href:f},g)}}};i.pah=function pah(b,c,d){if(Q.ie||P(d)){var e,f;try{F.push(c);for(e in c){f=
c[e];var g=document.getElementById(e);if(!g)continue;if(!g.orighref){var j=g.href.indexOf("?");if(j>=0)g.orighref=g.href.substr(0,j+1);else g.orighref=g.href}g.href=g.orighref+f}}catch(s){H("PAH",{id:e,suffix:f},s)}}};i.pa=function pa(b,c,d,e){if(Q.ie||P(e)){try{var f=document.getElementById(c),g=document.createElement("div");g.innerHTML=d;for(var j;j=g.firstChild;)f.appendChild(j);if(Q.ie)ha(d)}catch(s){H("PA",{id:c},s)}D=22}};function ia(b,c){for(var d in c){var e=c[d];if(e&&typeof e=="object"){if(!b[d]||
typeof b[d]!="object")b[d]={};ia(b[d],e)}else b[d]=e}}i.sa=function sa(b,c,d,e){if(Q.ie||P(e))try{var f=document.getElementById(c);ia(f,d)}catch(g){H("SA",{id:c,elt:f,attbs:T(d)},g)}};var U=1,Q={},O,V=1;function ja(){if(window.opera)return"opera";if(document.all)return"ie";if(/Gecko/.test(navigator.userAgent))return"gecko";return""}Q[ja()]=1;function ka(){return/#.+/.test(X())?X():m.href.substr(m.href.indexOf("?")).replace(/#.*/,"")}function S(b,c){try{var d=c||ka(),e=d.match("[?&#]"+b+"=(.*?)([&#]|$)");
if(e)return decodeURIComponent(e[1].replace(/\+/g," ").replace(/[\n\r]+/g," "))}catch(f){H("GQC",{c:b},f)}return""}i.ad=function ad(b,c,d,e,f,g){var j=false;if(Q.ie){n=b;i.ss=N();I(m,n)}if(Q.ie||P(f)){la();ma();try{k.document.title=(document.title=c)}catch(s){}google.kEI=d;if(g)if(typeof g=="object")google.kCSI=g;else google.kCSI.e=g;if(r!=e)j=na(e,b);else j=true;o=S("q",b)||o;B="";E=[];F=[];D=20}return j};i.zd=function zd(b,c,d,e,f,g){if(Q.ie||P(g)){A=c;x=d;y=e;w=f}};i.zz=function zz(b,c){if(Q.ie||
P(c)){google.timers&&google.timers.load.t&&(google.timers.load.t.prt=(new Date).getTime());if(Q.gecko)oa(b);t.c[r].nb&&qa();ra();U=1;if(google.timers&&google.timers.load.t){google.timers.load.t.ol=(new Date).getTime();google.timers.load.t.jsrt=O;K&&google.report&&google.report(google.timers.load,{ei:google.kEI,e:google.kCSIE||google.kEXPI,cp:M})}i.d=i.ss;if(Q.gecko)k.src="about:blank"}K=false;D=0};function sa(){google.pageState=n;for(var b=0,c;c=google.rein[b++];)try{c(n=="#",L)}catch(d){H("INJS",
{i:b},d)}}function ma(){if(google.y.x)google.x=google.y.x;for(var b=0,c;c=google.dstr[b++];)try{c()}catch(d){H("DEJS",{i:b},d)}}i.l=function l(){try{var b=k.location.href}catch(c){Y(n);return}try{if(!(/\/blank\.html$/.test(b)||/about:blank$/.test(b))&&!(k.google&&k.google.loc))if(u.test(b))Y(ka());else I(m,b,1)}catch(c){H("_l",{},c)}};function Y(b){b="/search?"+b.substr(1).replace(/(^|&)fp\=[^&]*/g,"")+"&emsg=NCSR&ei="+window.google.kEI;try{window.onerror(["NCSR:_g",!(!k.google),"_lg",O?(new Date).getTime()-
O:"NA","_sl",V,"_fl",k.location.href].join(":"))}catch(c){}I(m,b,1)}i.e=function er(b){H("IFE",{},b||window.event)};function ga(b,c){if(!h)return true;var d="#";try{if(c)d+=b.href.match(/\?(.*)/)[1];else{var e=[];b.q&&b.q.blur();var f=null;for(var g=0,j;j=b.elements[g++];){if((j.type=="radio"||j.type=="submit")&&!j.checked)continue;if(j.name=="btnI")return true;if(j.name=="oq")f=j.name+"="+encodeURIComponent(j.value);else if(j.name)e.push(j.name+"="+encodeURIComponent(j.value))}f&&e.push(f);d+=e.join("&").replace(/\%20/g,
"+")}d=d.replace(/\'/g,"%27");var s=S("q",d);if(!s)return false;if(/(^| )(r?phonebook|define|cache):/.test(s)||/(\?|&)pb=(r|f)/.test(d)||/(\?|&)swm=2/.test(d))return true}catch(z){H("HSA",{t:b.tagName},z);return true}d+="&fp="+(r=="1"?da:r);if(Q.gecko)I(m,d);K=true;delete t.s[d];document.getElementById("csi").value="";Z(d);if(Q.ie)I(m,d);return false}function ta(b){var c=X(b);if(U&&c!=n&&ea.test(m.href)){K=!(c in t.s);document.gs&&document.gs.q.blur();document.bgs&&document.bgs.q.blur();document.f&&
document.f.q.blur();if(Q.gecko||b||c=="#"){try{if(b&&i.b){var d=!document.getElementById("csi").value;i.b=0;if(Q.ie&&n=="#"||Q.gecko&&d){c=$(c,"fp","1");if(c.indexOf("&fp=")==-1)c+="&fp=1";if(c.indexOf("&cad=")==-1)c+="&cad=b";delete t.s[c];if(Q.gecko)I(m,c)}}}catch(e){}Z(c,b)}if(Q.ie)I(m,c)}window.setTimeout(ta,100)}function Z(b,c){O=(new Date).getTime();J=false;M=(L=false);google.timers.load.t=null;if(b!="#"&&b.indexOf("&fp=")==-1){b+="&fp="+r;I(m,b,1)}n=b;if(!Q.ie)i.ss=N();V=0;try{U=0;var d=b.substr(1);
if(Q.ie&&b=="#"){if(b in t.s){R(r);ua(b)}}else if(Q.ie&&!c){J=true;I(k.location,"/search?"+d)}else if(Q.gecko&&b in t.s){R(r);ua(b)}else if(b!="#"){J=true;I(k.location,"/search?"+d,true)}}catch(e){V=1;H("GO",{o:c,s:b},e)}window.setTimeout(function(){V=1},50)}function R(b){if(t.c[b].pc)try{document.getElementById("resultStats").style.visibility="hidden"}catch(c){}var d="";try{for(var e=0;d=t.c[b].cc[e++];)document.getElementById(d).style.visibility="hidden"}catch(c){H("C",{fp:b,c:d},c)}}function T(b){var c=
"",d;switch(typeof b){case "object":if(b instanceof Array){for(d=0;d<b.length;d++){if(c)c+=",";c+=T(b[d])}return"["+c+"]"}else{for(d in b){if(c)c+=",";c+=T(d)+":"+T(b[d])}return"{"+c+"}"}case "number":return String(b);case "string":c=b.replace(/\\/g,"\\\\").replace(/\'/g,"\\'").replace(/\n/g,"\\n").replace(/\r/g,"\\r");return"'"+c+"'";case "boolean":return String(b);default:return"null"}}function oa(b){if(!t.s[b]){var c;try{var d={};for(var e=0,f;f=t.c[r].co[e++];){c=f;d[f]=document.getElementById(f).innerHTML}d.title=
document.title;d.kEI=window.google.kEI;d.base_href=w;d.end=x;d.num=y;d.start=A;if(!t.c[r].pc){d.phs=E;d.pahs=F}d.chrome=r;d.bc=B;t.s[b]=d}catch(g){H("S",{s:b,c:c},g)}}va(r,b)}function va(b,c){try{if(aa){if(c){sessionStorage["s_"+c]="("+T(t.s[c])+")";var d=sessionStorage.s_?eval(sessionStorage.s_.value):[];d.push(c);sessionStorage.s_=T(d)}if(b){sessionStorage["c_"+b]="("+T(t.c[b])+")";var e=sessionStorage.c_?eval(sessionStorage.c_.value):[];e.push(b);sessionStorage.c_=T(e)}}else document.getElementById("wgjc").value=
"("+T(t)+")"}catch(f){document.getElementById("wgjc").value="({})";H("SE",{s:c,c:b,ss:!(!window.sessionStorage)},f)}}function wa(){try{if(aa){t={s:{},c:{1:i[1]}};var b=sessionStorage.s_?eval(sessionStorage.s_.value):[],c=sessionStorage.c_?eval(sessionStorage.c_.value):[];for(var d=0,e;e=b[d++];)t.s[e]=eval(sessionStorage["s_"+e].value);for(var f=0,g;g=c[f++];)t.c[g]=eval(sessionStorage["c_"+g].value)}else t=window.eval(document.getElementById("wgjc").value)}catch(j){H("RC",{},j)}if(!t)t={s:{},c:{1:i[1]}}}
function la(){if(google.timers&&!google.timers.load.t){google.sn="web";google.timers.load.t={start:(new Date).getTime()}}}i.ac=function ac(b,c,d,e,f,g){if(Q.ie||P(g)){if(!e){t.c[c]={};for(var j in b)t.c[c][j]=b[j]}if(d){M=(L=true);la();if(Q.ie)document.styleSheets[0].cssText=t.c[c].css;else document.getElementsByTagName("style")[0].innerHTML=t.c[c].css}D=10}};i.pc=function pc(b,c,d,e,f,g,j){if(Q.ie||P(j)){try{if(!f)t.c[d][b]=c;if(e){i.p(n,b,c,j);document.body.style.visibility=""}}catch(s){H("PC",
{c:b,f:d},s)}D=11}};i.zc=function zc(b,c,d,e,f,g){if(Q.ie||P(g)){if(!e){for(var j in b)t.c[c][j]=b[j];if(Q.ie)va(c)}if(d)r=c;else da=c;D=12}};function na(b,c){if(t.c[b]){i.ac({},b,1,1,n,0);M=false;i.pc("main",t.c[b].main,b,1,1,n,0);i.zc({},b,1,1,n,0)}else{var d=S("fp",c)||"1";H("CM",{fp:d});if(d!="1")Z($(c,"fp","1"));else Y(c);return false}return true}function ua(b){try{window.google.kEI=t.s[b].kEI;try{k.document.title=(document.title=t.s[b].title)}catch(c){}if(t.s[b].chrome!=r)if(!na(t.s[b].chrome,
b))return;ma();i.bc(t.s[b].bc);for(var d=0,e;e=t.c[t.s[b].chrome].co[d++];)i.p(b,e,t.s[b][e]||"",0);w=t.s[b].base_href;x=t.s[b].end;y=t.s[b].num;A=t.s[b].start;t.c[r].nb&&qa();ra();o=S("q",b)||o;E=[];F=[];if(!t.c[t.s[b].chrome].pc){if(t.s[b].phs)for(var d=0,f;f=t.s[b].phs[d++];)i.ph(b,f,0);if(t.s[b].pahs)for(var d=0,g;g=t.s[b].pahs[d++];)i.pah(b,g,0)}D=0;i.d=i.ss;U=1}catch(c){H("DPFC",{s:b},c)}}i.xi=function xi(){if(google.y.first){for(var b=0,c;c=google.y.first[b];++b)c();google.y.first=[]}google.x=
function(d,e){e&&e.apply(d);return false};sa()};function xa(){try{var b=k.location.href,c=b.indexOf("?");return c>=0?"#"+b.substr(c+1):"#"}catch(d){H("FQS",{},d);return n||"#"}}function X(b){if(!b&&Q.ie)return xa();else return m.hash?m.href.substr(m.href.indexOf("#")):"#"}function ya(){var b=0;try{var c=document.getElementById("resultStats").innerHTML.replace(/<a.*?>.*?<\/a>/i,"");c=c.replace(/\(.*?\)/,"");c=c.replace(/\.|,|&nbsp;|'/g,"");var d=c.match(/\d+/g),e=0,f;for(f=0;f<d.length;++f){var g=
parseInt(d[f]);if(g>e)e=g}b=e}catch(j){}return b}function $(b,c,d){var e=new RegExp("([?&]"+c+"=).*?([&#]|$)");return b.replace(e,"$1"+encodeURIComponent(d).replace(/\%20/g,"+")+"$2")}function ra(){try{var b=S("q")||S("as_q")||o,c=S("restrict"),d=ya(),e=t.c[r].pc;for(var f=0,g;g=["gs","bgs","f"][f++];)if(document[g])document[g].q.value=b;if(e)for(var f=0,j;j=e[f++];){var s=document.getElementById(j)?document.getElementById(j).getElementsByTagName("a"):[];for(var z=0,v;s&&(v=s[z++]);){v.href=$(v.href,
"q",b);v.href=$(v.href,"swrnum",d);if(c)v.href=$(v.href,"restrict",c)}}}catch(G){H("PQ",{},G)}i.trap()}function Ba(b,c,d,e){var f={a:b.getElementsByTagName("a")[0],e:b,s:b.getElementsByTagName("span")[0],l:b.getElementsByTagName("span")[1]};f.a.href=w.replace(/start=\d*/,"start="+c);f.s.style.backgroundPosition=-[26,0,44,60,76,76][d]+"px 0";f.s.style.width=[18,44,16,16,66,42][d]+"px";f.s.style.marginLeft=d==1?"auto":"";f.s.style.marginRight=d==4?"34px":"";f.s.className=d==2?"csb":"csb ch";f.l.style.color=
d==2?"#a90a08":"";f.l.style.display=e;return f}function qa(){try{var b=S("start")||0;if(x<b)b=x;var c=document.getElementById("nav"),d=document.getElementById("foot");if(!c){d.style.visibility="visible";return}var e=c.getElementsByTagName("td"),f=Math.floor(A/y)+1,g=Math.floor(b/y)+1,j=Math.ceil(x/y),s=b<y,z=g>=j;if(f<j){c.style.display="";var v=e[1],G=e[e.length-1];Ba(e[0],Math.max((g-2)*y,0),s?0:1,s?"none":"");Ba(G,g*y,z?5:4,z?"none":"");for(var C=1,za=e.length-1;C<za;C++)G.parentNode.removeChild(e[1]);
for(var C=f;C<=j;C++){var ba=C==g,W=Ba(v.cloneNode(true),(C-1)*y,ba?2:3,"");W.e.className=ba?"cur":"";W.a.style.textDecoration=ba?"none":"";W.l.innerHTML=C;G.parentNode.insertBefore(W.e,G)}}else c.style.display="none";d.style.visibility="visible"}catch(Aa){H("RNB",{},Aa)}}function Ca(b){ea=new RegExp("^"+b);u=new RegExp("(^"+b+"|^)/search(\\?|$)")}function Da(b){if(!h)return true;b=b||window.event;if(b.altKey||b.ctrlKey||b.shiftKey||b.metaKey||b.button&&b.button!=0)return true;var c=b.target||b.srcElement;
while(c&&c.nodeName.toLowerCase()!="body"){if(c.nodeName.toLowerCase()=="a"){if(c.target)return true;else if(u.test(c.href)&&!/\bnj\b/.test(c.className)){var d=ga(c,true);d===false&&b.preventDefault&&b.preventDefault();return d}else if(/&rct=j/.test(c.href))try{google.r=1;k.location.replace(c.href);b.preventDefault&&b.preventDefault();return false}catch(e){return true}break}c=c.parentNode}}function Ea(){h=i.en&&i[1]&&encodeURIComponent&&k&&google.rein&&google.dstr&&1;if(h){var b=["wgjc"].concat(t.c[1].co);
for(var c=0;c<b.length;c++)h&=!(!document.getElementById(b[c]))}try{if(h){n=Q.gecko?"#":X();O=(new Date).getTime();i.ss=(i.d=N());var d=m.href.match(/.*?:\/\/[^\/]*/)[0];Ca(d);i.trap();google.bind(document,"click",Da);if(m.hash&&m.hash!="#")R(r);wa();oa("#");window.wgjp&&window.wgjp();if(!Q.gecko||i.b)for(var e=0,f;f=i.pl[e++];){var g=i[f[0]].apply(null,f[1]);if(f[0]=="ad"&&!g)i.pl=[]}if(Q.ie&&n=="#")try{k.document.title=document.title}catch(j){}ta(1)}else{if(google.j.en!=0)H("INIT1",{});window._gjp&&
window._gjuc&&window._gjp()}}catch(j){H("INIT2",{},j);h=false;window._gjp&&window._gjuc&&window._gjp()}}Ea();
})();
if(!window.gbar||!gbar.close){window.gbar={};(function(){var g=window.gbar,j,k;function l(a){var d=window.encodeURIComponent&&(document.forms[0].q||"").value;if(d)a.href=a.href.replace(/([?&])q=[^&]*|$/,function(h,f){return(f||"&")+"q="+encodeURIComponent(d)})}g.qs=l;function m(a,d,h,f,b,c){var i=document.getElementById(a),e=i.style;if(i){e.left=f?"auto":d+"px";e.right=f?d+"px":"auto";e.top=h+"px";e.visibility=k?"hidden":"visible";if(b){e.width=b+"px";e.height=c+"px"}else{m(j,d,h,f,i.offsetWidth,i.offsetHeight);k=k?"":a}}}g.tg=function(a){a=a||window.event;var d=0,h,f=window.navExtra,b,c=a.target||a.srcElement;a.cancelBubble=true;if(c.className!="gb3")c=c.parentNode;if(!j){b=document.createElement(Array.every||window.createPopup?"iframe":"div");b.frameBorder="0";b.src="#";j=c.parentNode.appendChild(b).id="gbs";document.onclick=g.close}a=c.getAttribute("aria-owns")||"gbi";b=c.offsetWidth;var i=c.offsetTop>20?46:24,e;do d+=c.offsetLeft||0;while(c=c.offsetParent);if(a=="gbi")for(b=document.getElementById(a);f&&(h=f.pop());)b.insertBefore(h,b.firstChild).className="gb2";else e=d=(document.documentElement.clientWidth||document.body.clientWidth)-d-b;k!=a&&g.close();m(a,d,i,e)};g.close=function(){k&&m(k,0,0)}})();;};
(function (){
var a="google";if(window[a]){window[a].a={};window[a].b=1;window[a].report=function(h,g,i){var d="";{if(window[a].pt){d+="&srt="+window[a].pt;delete window[a].pt}try{d+="&tran="+window.external.tran}catch(n){}}{var j=document.getElementById("csi");if(j.value)return;j.value=1}var b=h.t,e=b.start;delete b.start;var k=[];for(var f in b)e&&k.push(f+"."+(b[f]>e?b[f]-e:e-b[f]));if(g)for(var l in g)d+="&"+l+"="+g[l];var c=new Image,m=window[a].b++;window[a].a[m]=c;c.onload=(c.onerror=function(){delete window[a].a[m]});
c.src=[i?i:"/csi","?v=3","&s="+(window[a].sn?window[a].sn:"GWS")+"&action=",h.name,d,"&rt=",k.join(",")].join("");c=null}};window.setTimeout(function(){if(google.timers&&google.timers.load.t){google.timers.load.t.xjs=(new Date).getTime();google.timers.load.t.ol&&google.report(google.timers.load,google.kCSI)}},0);
})();
window.clk=function(b,c,d,e,f,g,h){if(document.images){var a=encodeURIComponent||escape;(new Image).src=["/url?sa=T","&source="+google.sn,c?"&oi="+a(c):"",d?"&cad="+a(d):"","&ct=",a(e||"res"),"&cd=",a(f),b?"&url="+a(b.replace(/#.*/,"")).replace(/\+/g,"%2B"):"","&ei=",google.kEI,g].join("")}
return true};
window.rwt=function(a,g,h,k,l,i,m,n){try{if(a===window)for(a=window.event.srcElement;a;){if(a.href)break;a=a.parentNode}var b=encodeURIComponent||escape,e=a.href.split("#"),c=0;if(!google.njr)for(var d=location.href.split("#"),j=0;j<2&&!c;j++){c=d&&d[1]&&d[1].match("(^|&)q=(.*?)(&|$)");d=location.href.split("?")}var f=["/url?sa=t","&source="+google.sn,g?"&oi="+b(g):"",h?"&cad="+b(h):"","&ct=",
b(k||"res"),"&cd=",b(l),"&url=",b(e[0]).replace(/\+/g,"%2B"),"&ei=",google.kEI,i?"&usg="+i:"",m,e[1]?"#"+e[1]:""].join("");if(!google.njr&&c){var o=("&rct=j&q="+c[2]).substring(0,1948-f.length);a.href=f.replace(/&usg=/,o+"&usg=")}else a.href=f;a.onmousedown=""}catch(p){}return true};
if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.y.x=google.x;google.x=function(d,c){c&&c.apply(d);return false};google.y.first=[];
